project:
  type: book

book:
  title: "Shiny App-Packages"
  author: "Martin Frigaard"
  description: |
    Getting your app into an R package
  reader-mode: true
  site-url: https://mjfrigaard.github.io/shiny-app-pkgs/
  repo-url: https://github.com/mjfrigaard/shiny-app-pkgs
  repo-branch: main
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    - preface.qmd
    - part: intro.qmd
      chapters:
        - whole_game.qmd
        - shiny.qmd
        - packages.qmd
        - development.qmd
    - part: app_packages.qmd
      chapters:
        - document.qmd
        - dependencies.qmd
        - data.qmd
        - launch.qmd
        - external.qmd
    - part: tests.qmd
      chapters:
        - test_suite.qmd
        - test_specs.qmd
        - test_tools.qmd
        - test_modules.qmd
        - test_system.qmd
    - part: deploy.qmd
      chapters:
        - docker.qmd
        - gha.qmd
        - pkgdown.qmd
    - part: code.qmd
      chapters:
        - css.qmd  
        - js.qmd
        - python.qmd
        - style.qmd
    - part: frameworks.qmd
      chapters:
        - golem.qmd
        - leprechaun.qmd
        - rhino.qmd
    - part: special_topics.qmd
      chapters:
        - debugging.qmd
        - app_data.qmd
        - stack_traces.qmd
        - entanglement.qmd

  appendices:
    - glossary.qmd
    - github.qmd
    - create.qmd
    - bdd.qmd
    - test_snapshots_mocks.qmd
    - comparisons.qmd
    - rhino_cicd.qmd
    

    

format:
  html:
    theme: [cosmo, custom.scss]
    highlight-style: arrow
    toc: true
    toc-depth: 5
    toc-location: right
    toc-title: Contents
    code-overflow: scroll
    code-link: false
    code-block-bg: "#f8f8f8"
    code-block-border-left: "#99bbc9"
    code-annotations: hover
    number-sections: true
    callout-icon: false
    code-fold: show
    code-summary: 'show/hide'
    df-print: tibble
    dpi: 320
    fig-format: retina
    fig-asp: 0.618
    fontsize: 1.085em
    linestretch: 1.25



