project:
  type: book

book:
  title: "Shiny App-Packages"
  author: "Martin Frigaard"
  description: |
    Get your app in a R package
  date: "8/17/2023"
  reader-mode: true
  page-navigation: true
  site-url: https://mjfrigaard.github.io/shinyap/
  repo-url: https://github.com/mjfrigaard/shinyap
  repo-branch: main
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - shiny.qmd
        - packages.qmd
        - devtools.qmd
    - part: app_packages.qmd
      chapters:
        - roxygen2.qmd
        - dependencies.qmd
        - app.qmd
        - data.qmd
        - inst_www.qmd
        - tests.qmd
    - part: frameworks.qmd
      chapters:
        - golem.qmd
        - leprechaun.qmd
        - rhino.qmd
    - part: special_topics.qmd
      chapters:
        - debugging.qmd
        - css.qmd
        - js.qmd
        - code_tools.qmd

  appendices:
    - glossary.qmd
    - github.qmd
    - create.qmd

# callout-icon: false

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [cyborg, custom.scss]
    highlight-style: 
      light: arrow-light
      dark: arrow-dark
    toc: true
    toc-depth: 5
    toc-location: right
    toc-title: Contents
    code-overflow: wrap
    code-link: true
    code-block-bg: "#f8f8f8"
    code-block-border-left: "#e8e8e8"
    fig-align: center
    code-fold: show
    code-summary: 'show/hide'
    df-print: paged
    dpi: 320
    fig-format: retina
    fig-asp: 0.618
    fontsize: 1.075em
    linestretch: 1.25



